# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3  # Number of replicas (pods)
  selector:
    matchLabels:
      app: my-app  # Label selector to match pods
  template:
    metadata:
      labels:
        app: my-app  # Same label as in the selector
    spec:
      containers:
      - name: my-app
        image: my-app-image:latest
        ports:
        - containerPort: 80  # Expose port 80 on each pod
