apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # Matches the pods with the label app=my-app
  ports:
    - protocol: TCP
      port: 80  # Expose service on port 80
      targetPort: 80  # Forward traffic to container's port 80
  type: ClusterIP  # Internal load balancing (default)
